language: python

python:
- '2.7'

install:
- pip install -r requirements.txt
- pip install -r requirements-dev.txt

script:
- pep8
- nosetests

deploy:
  provider: pypi
  # server: https://testpypi.python.org/pypi
  user: marco.lovato
  password:
    secure: xrJxZMnzeXHszYt1g7xLiPzxkHbsP2Tjj6fjvDK3iPMN0wlnGfhDmYEV5cVPMzkpTi1T9mtatoB2BjTDZL7fuEdSv59mvP39soj8qqj/i6opOCQqepvDPRMaCCq7hT/ViUcgSho9h5NBTiHvblhtrOic+hZTVVjt2nG4uCP2af0=
  on:
    repo: lovato/machete

notifications:
    email: true

after_success:
- coveralls